### ISSUE TITLE
Support audio-only calls

### ISSUE THREAD

**Issue by superdump** [matrix-org/matrix-vr-demo#17]
In some cases people don't want to do video chat but perhaps want to do audio chat - we could allow audio-only calls and present some ball-of-light type avatar to represent their presence.

**Comment by ara4n** [comment]
The real issue here is that if a user doesn't share their webcam, everything breaks with no explanation.  This has screwed up a few of my demos.  At least warning when this happens would be good - better would be to go the full hog and support audio calls.

**Comment by superdump** [comment]
I have a small modification to the matrix-js-sdk that enables receiving audio and video even if gUM returns a `MediaStream` with only an audio track. This will allow users who do not have a camera to invite people to / answer video calls while only sending audio themselves. Application UI/UX may need work (and indeed I'll have to do something to make it work well in VR.)

If a user has a camera, or has one embedded in their device however, they will need to explicitly not request video from gUM while still requesting to receive audio/video when creating their offer / answer. I have also implemented the necessary machinery in the JS SDK locally to do this but would need to hook it up to some user input in the VR demo to choose whether to make a call with audio and video, or only audio.

**Comment by ara4n** [comment]
the important scenarios are: the user has no webcam, or the user has a webcam but explicitly denies it access to the site.

the user who has a camera but wants to do a recv-only video call without being prompted for permission to use the webcam is an edge case we don't care that much about.

hope this helps :S

**Comment by superdump** [comment]
OK. I'll push up those changes on top of the branch we have against the JS SDK and bump the commit used in package.json. Thanks.

**Comment by superdump** [comment]
What remains to be done for this is to make sure the audio-only case is presented sensibly in the UI.

**Comment by superdump** [comment]
<img width="1672" alt="screen shot 2017-04-13 at 15 02 01" src="https://cloud.githubusercontent.com/assets/302146/25005694/31753e30-205a-11e7-9de8-5f6890dc59e8.png">

The left-side is Chrome configured to disallow camera access to any page and so it only offers to send audio but receive audio/video. The right-side is Firefox Dev Edition (54 currently - aurora channel IIRC) sending audio/video and receiving only audio. I have checked and that is actually what is happening.

It seems that on the left side the loadedmetadata on the remote video element has fired, which made the call become active, which triggered the rendering of the video planes in the ConferenceView. The local camera view is black because camera access is disallowed. We can either present a black plane or present something else.

The loadedmetadata event has not been fired on the right side however so it seems it is not fired for audio only streams on a video element.

I wrangled a bit with the internals of MatrixCall to try to get it to assign the audio stream to the remote video element but the various things I had time to try today seemed to degrade the experience from where it is. More next week.

**Comment by ara4n** [comment]
i think the solution here is probably to split audio & video paths into entirely separate `<audio/>` and `<video/>` elements (which is something I had to do in riot-web at some point, to let the video element bounce around the DOM without interrupting audio).

**Comment by superdump** [comment]
They already are on separate paths. There's a weird cross-over if the remote stream contains only audio tracks where the type gets switched to voice. If you then haven't set any remote audio element, other code paths based on the call type break a bit. I'm looking into more solutions.

**Comment by superdump** [comment]
Fixed in:
* https://github.com/matrix-org/matrix-js-sdk/commits/rob/audio-only-video
* #55 

Now looks like:
<img width="1680" alt="screen shot 2017-04-19 at 11 26 54" src="https://cloud.githubusercontent.com/assets/302146/25174222/f6c8db06-24f6-11e7-931b-f7ff2f5bfdc9.png">
