### ISSUE TITLE
Prevent joining VC room before it is ready

### ISSUE THREAD

**Issue by rxl881** [matrix-org/matrix-vr-demo#20]
We need to wait for VC room to be initialised (created + alias) before participants can enter.

* Wait for room creation and room alias to be provided
* Disable phonebox hitbox until initialised
* Make phonebox model semi-transparent / remove model texture until ready
* Play audio when conf. is ready?

**Comment by superdump** [comment]
It is first here that we have successfully joined the room and we set the `roomId`: https://github.com/matrix-org/matrix-vr-demo/blob/master/src/js/components/structures/FullMeshConference.js#L74

I'd suggest using the same pattern as in other cases where we check if the `roomId` is set and if not, wait for some event that is emitted just after the `roomId` is set there.

**Comment by rxl881** [comment]
As mentioned in PR #27, we might not need to use the event (for now at least).

**Comment by rxl881** [comment]
Fixed in #27.
