### ISSUE TITLE
Loop the ringback tone sequence

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-vr-demo#42]
It sucks that it only shows for a few seconds before disappearing forever, given the whole point is that it's meant to keep the user entertained (and make the demo work) whilst waiting for the other user to join.

**Comment by superdump** [comment]
Looping done. Ben is going to record a couple more videos to use in a spaced playlist on loop. I'll sort out the remainder of this when those are ready.

**Comment by superdump** [comment]
Added some more videos in #47 . They refer to 'being connected' with your guide. If you haven't set a guide then these videos are going to be weird.

**Comment by superdump** [comment]
I've made it so that the Welcome video will loop if there is no call, or if all the videos have played through once. The latter case is a tweak as the call will have timed out when the videos have played through once and so we are no longer trying to connect.
